src/controller.js
tests/controller.js
tests/view.js

Destroy the controller's children correctly

---

src/editableui/editableuiview.js
src/iconmanagerview.js
src/template.js
src/view.js
tests/iconmanagerview.js
tests/template.js
tests/view.js

t/20: Allow creating SVG elements via Template class

---

src/controller.js
src/domemittermixin.js
src/editorui/editorui.js
src/model.js
src/view.js
tests/creator-utils.js

https://github.com/ckeditor/ckeditor5-ui/pull/23 -> clkeditor5-utils#12
Connected to https://github.com/ckeditor/ckeditor5-utils/pull/29

Use of utils object refactor

---

src/domemittermixin.js
src/editableui/inline/inlineeditableuiview.js
src/editorui/boxed/boxededitorui.js
src/editorui/boxed/boxededitoruiview.js

Changed absolute import paths to relative.

---

src/editorui/boxed/boxededitoruiview.js
src/region.js
tests/region.js

Related to https://github.com/ckeditor/ckeditor5-ui-default/issues/12.

t/ckeditor5-ui-default/12: Implement dropdown component

---

src/editableui/editableui.js

Added missing model interface docs for EditableUI class.

---

src/template.js
tests/template.js

Support for binding styles to view model props

---

src/controller.js
tests/controller.js

t/52: Simplified Controller#addCollection locale management

---

src/template.js
tests/editableui/editableuiview.js
tests/template.js

t/47: A new approach to falsy values in Template definition

---

src/bindings/stickytoolbar.js
src/bindings/toolbar.js
src/componentfactory.js
src/controllercollection.js
src/editableui/editableui.js
src/editableui/editableuiview.js
src/editableui/inline/inlineeditableuiview.js
src/editorui/boxed/boxededitorui.js
src/editorui/editorui.js
src/editorui/editoruiview.js
src/view.js
tests/bindings/stickytoolbar.js
tests/bindings/toolbar.js
tests/bindings/toolbarbindingsmixin.js
tests/boxededitorui/boxededitorui.js
tests/componentfactory.js
tests/controller.js
tests/controllercollection.js
tests/domemittermixin.js
tests/editableui/editableui.js
tests/editorui/editorui.js
tests/iconmanager/iconmanagerview.js
tests/template.js
tests/view.js

Changed paths and docs to use ckeditor5-core package

---

src/editableui/editableui.js
src/editableui/editableuiview.js
src/iconmanager/iconmanager.js
src/iconmanager/iconmanagerview.js

t/44: Added missing @observable documentation tag to various model attributes.

---

.jshintrc
src/editorui/editoruiview.js
src/iconmanager/iconmanagerview.js
tests/.jshintrc
tests/_utils-tests/utils.js
tests/_utils/utils.js
tests/controller.js
tests/controllercollection.js
tests/domemittermixin.js
tests/editableui/editableui.js
tests/editableui/editableuiview.js
tests/editableui/inline/inlineeditableuiview.js
tests/editorui/editoruiview.js
tests/template.js

Turn JSHint browser setting to false.

---

tests/componentfactory.js
tests/controller.js
tests/controllercollection.js
tests/template.js
tests/view.js

Fixes: https://github.com/ckeditor/ckeditor5-ui/issues/64.

Updated tests with `throwCKEditorError` check

---

src/domemittermixin.js

Fixes #79 
Depends on: https://github.com/ckeditor/ckeditor5-utils/issues/76

Changed DOMEmiterMixin docs after EmiterMixin refactoring.

---

src/template.js
tests/template.js

t/70: Template class refactoring for better child management 

---

src/domemittermixin.js
tests/domemittermixin.js

Added event capturing option to DOMEmitterMixin.

---

src/domemittermixin.js
tests/domemittermixin.js

Fixed stopListening method of DOMEmitterMixin

---

tests/template.js

Tests: changed problematic test (see #85).

---

src/template.js
src/view.js
tests/controllercollection.js
tests/view.js

Fixes #73 
Related to:
- https://github.com/ckeditor/ckeditor5-ui-default/issues/94
- https://github.com/ckeditor/ckeditor5-link/issues/50

Removed model from View class

---

src/controllercollection.js
tests/controllercollection.js

t/92: It should be possible to skip some elements on the collection binding

---

src/controller.js
src/template.js
tests/controller.js
tests/template.js

t/88: Allow using Views directly in TemplateDefinition

---

src/controllercollection.js
tests/controllercollection.js

t/96: Incorrect order management in ControllerCollection bound to another collection

---

src/view.js
tests/view.js

Renamed View.addChild() -> View.addChildren() with iterable interface.

---

src/viewcollection.js
tests/viewcollection.js

t/92: Fixed: A View#id Number breaks parent ViewCollection.

---

theme/components/balloonpanel.scss
theme/components/button.scss
theme/components/dropdown.scss
theme/components/editor.scss
theme/components/icon.scss
theme/components/label.scss
theme/components/list.scss
theme/components/reset.scss
theme/components/stickytoolbar.scss
theme/components/toolbar.scss
theme/components/tooltip.scss
theme/helpers/_editor.scss
theme/helpers/_states.scss
theme/helpers/_zindex.scss
theme/theme.scss

Extracted wireframe theme from Lark.

---

src/dropdown/dropdownview.js
src/viewcollection.js
tests/viewcollection.js

t/145: Fixed ViewCollection and DOM desynchronise in some cases.

---

theme/helpers/_states.scss

Other: Imported "ck-hidden" CSS class from ckeditor5-theme-lark. Closes #164.

t/164: Imported ck-hidden class from ckeditor5-theme-lark.

---

src/dropdown/list/createlistdropdown.js
src/viewcollection.js
tests/viewcollection.js

Other: Moved ViewCollection#bindTo method to Collection class in ckeditor5-utils. Closes #168.

T/168: Moved ViewCollection#bindTo method to Collection class in ckeditor5-utils

---

src/componentfactory.js
tests/componentfactory.js

Other: Throw an error when attempting to create a component not registered in ComponentFactory. Closes #174.

t/174: Throw an error when attempting to create a component not registered in ComponentFactory

---

src/view.js
src/viewcollection.js
tests/view.js
tests/viewcollection.js

Fix: ViewCollection#destroy should wait for all ViewCollection#add promises to resolve to avoid errors. Closes #203.

t/203: ViewCollection#destroy should wait for all ViewCollection#add promises to resolve to avoid errors. Closes #203.

---

src/bindings/preventdefault.js
src/focuscycler.js
src/panel/balloon/balloonpanelview.js
src/toolbar/toolbarview.js
tests/bindings/preventdefault.js
tests/focuscycler.js
tests/panel/balloon/balloonpanelview.js
tests/toolbar/toolbarview.js

Fix: BalloonPanelView should not be focusable. Closes #206.

T/206a: BalloonPanelView should not be focusable

---

src/inputtext/inputtextview.js
tests/inputtext/inputtextview.js

Feature: Implemented placeholder in `InputTextView`. Closes #220.

t/220: Implemented placeholder in InputTextView

---

src/notification/notification.js
tests/notification/notification.js

Feature: Added optional notification title. Closes #241.

Optional notification title

---

src/dropdown/dropdownview.js
tests/dropdown/dropdownview.js

Fix: DropdownView should open upon arrow down key press. Closes #249.

t/249: DropdownView should open upon arrow down key press. 

---

src/list/listitemview.js
tests/list/listitemview.js

Fix: List items should handle Enter and Space key press when focused. Closes #153.
Requires: ckeditor/ckeditor5-utils#169.

t/153: List items should handle Enter and Space key press when focused

---

src/inputtext/inputtextview.js
tests/inputtext/inputtextview.js

Fix: Improved binding of value attribute in InputTextView. Closes #335.

Fix: Improved binding of value attribute in InputTextView.

---

tests/template.js

Tests: Aligned tests to changes in view stringify utility. Read more https://githu…b.com/ckeditor/ckeditor5-engine/issues/1179.
---
See: https://github.com/ckeditor/ckeditor5-engine/pull/1184

Aligned tests to changes in view stringify utility

---

src/inputtext/inputtextview.js
tests/inputtext/inputtextview.js
tests/toolbar/contextual/contextualtoolbar.js

Tests: Fixed failed tests on other browsers than Chrome when using BrowserStack. Closes #334.

T/334: Fixed tests in order to run on BS

---

src/template.js

Other: Renamed isDomNode to isNode.

Rename isDomNode to isNode

---

docs/_snippets/examples/bootstrap-ui-inner.js
package.json

Docs: Enabled EasyImage in Bootstrap editor demo. Read more https://github.com/ckeditor/ckeditor5/issues/789.

Enabled EasyImage in Bootstrap editor demo

---

src/toolbar/normalizetoolbarconfig.js
tests/manual/tickets/228/1.js

Other: Align code to the changes in naming UI components & commands.
---
* Minor PR - Check: https://github.com/ckeditor/ckeditor5-alignment/pull/25.

Other: Align code to the changes in naming UI components & commands.

---

theme/globals/_zindex.css

Internal: Introduce relative z-index values. Closes #412.

Introduce relative z-index values.

---

src/panel/balloon/balloonpanelview.js
tests/panel/balloon/balloonpanelview.js

Internal: Fixed test, so it passes with webpack@4.
---
Required for https://github.com/ckeditor/ckeditor5-dev/pull/373.

Fix test, so it passes with webpack@4.

---

src/inputtext/inputtextview.js
src/labeledinput/labeledinputview.js
tests/inputtext/inputtextview.js
tests/labeledinput/labeledinputview.js
theme/components/labeledinput/labeledinput.css

Feature: Allowed displayin an error message next to the `LabeledInputVIew` (see ckeditor/ckeditor5-media-embed#1).
----
**A piece of https://github.com/ckeditor/ckeditor5-media-embed/pull/2 constellation.**

t/ckeditor5-media-embed/1: Allowed displayin an error message next to the LabeledInputVIew

---

tests/toolbar/balloon/balloontoolbar.js

Tests: Fixed failing tests after upgrading Sinon. See ckeditor/ckeditor5#1218.

Fixed usage of sinon.

---

tests/toolbar/balloon/balloontoolbar.js

Tests: Removed unnecessary timeouts from tests.
---
Part of the https://github.com/ckeditor/ckeditor5/issues/1202.

Remove unnecessary timeouts from tests

---

docs/_snippets/examples/bootstrap-ui-inner.js
docs/framework/guides/external-ui.md

Docs: Added missing comment to custom ui sample.
---
See https://github.com/ckeditor/ckeditor5-ui/pull/458#discussion_r249791801.

Docs: Added missing comment to custom ui sample

---

docs/_snippets/examples/bootstrap-ui-inner.js
docs/framework/guides/external-ui.md

Docs: Adjustments to new `data#ready` event.
---
See https://github.com/ckeditor/ckeditor5/issues/1477.

Adjustments to new `data#ready` event

---

theme/mixins/_rwd.css

Other: Moved `_rwd.css` file from `theme-lark` to `ui`. See ckeditor/ckeditor5#1662.

Moved _rwd.css from theme-lark to ui

---

src/panel/balloon/balloonpanelview.js

Docs: Add note about default limiter to BalloonPanelView#attachTo() method.
---
* I had some trouble understanding what happens there so I've added a small note.
* Also a typo was fixed.

T/ckeditor5 mention/37: Improve attachTo() docs

---

tests/manual/contextualballoon/contextualballoon.html
tests/manual/contextualballoon/contextualballoon.js
tests/manual/contextualballoon/contextualballoon.md

Test: Added a custom stack to the ContextualBalloon manual test. Closes #494.
---

Added a custom stack to the ContextualBalloon manual test.

---

src/notification/notification.js

Docs: Improve documentation for the notification plugin. Closes ckeditor/ckeditor5#1773.

Improve documentation for the notification plugin

---

src/panel/balloon/contextualballoon.js
tests/panel/balloon/contextualballoon.js

Other: Update rotator view counter message. Closes #508.
---
* I've also added translation tests so if not needed remove last commit.

T/508: The entire "%0 of %1" should be translated not only "of"

---

package.json
src/panel/balloon/contextualballoon.js
tests/manual/contextualballoon/contextualballoon.js
tests/manual/contextualballoon/contextualballoon.md
tests/panel/balloon/contextualballoon.js

Other: Implement single view mode for ContextualBalloon plugin.
---
* Part of a mention PR: https://github.com/ckeditor/ckeditor5-mention/pull/75

T/ckeditor5 mention/74: Add single view mode to contextual balloon.

---

theme/components/panel/balloonrotator.css
theme/components/panel/fakepanel.css

Internal: Updated the license header. See ckeditor/ckeditor5#1557. [skip ci]

Updated the license header

---

tests/toolbar/toolbarview.js

Tests: `ToolbarView` automatic items grouping test assertions should not fail when the browser window is not on the top. Closes ckeditor/ckeditor5#5603.

i/5603: Refactored ToolbarView tests so automatic items grouping assertions will no longer fail when browser window is not on the top

---

src/editorui/bodycollection.js
src/editorui/editoruiview.js
src/notification/notification.js
tests/editorui/bodycollection.js
tests/editorui/editoruiview.js
tests/notification/notification.js

Feature: Introduce a `BodyCollection` component. Closes ckeditor/ckeditor5#5888.
---
Requires https://github.com/ckeditor/ckeditor5-core/pull/204

BodyCollection component

---

src/formheader/formheaderview.js
tests/formheader/formheaderview.js
theme/components/formheader/formheader.css

Other: Cleaned up the component docs and code. Closes ckeditor/ckeditor5#6507.

I/6507: Clean up the form header component
