src/domemittermixin.js

Fixes #15.
`DOMEmitterMixin` used internal `_events` property of `EmitterMixin` which changed it's structure. Now it is used properly.

Changed: DOMEmitterMixin prepared to work with changed EmitterMixin.

---

src/iconmanager/iconmanagerview.js
tests/iconmanager/iconmanagerview.js

Fixes #55.
Note: Get the [latest VM](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/), then generate the bundle and test it in [developer sample code](https://github.com/CKEditor5/ckeditor5.github.io) instead of Bender suite, which is not compatible with Edge yet.

t/55: Edge does not render IconManager sprite.

---

src/button/buttonview.js
src/dropdown/createdropdown.js
tests/button/buttonview.js
tests/dropdown/createdropdown.js

Closes https://github.com/ckeditor/ckeditor5-ui/issues/119.
Closes https://github.com/ckeditor/ckeditor5-ui-default/issues/147.
Closes https://github.com/ckeditor/ckeditor5-ui-default/issues/148.
Closes https://github.com/ckeditor/ckeditor5-ui-default/issues/150.

t/119: New tooltip architecture

---

tests/template.js

Tests: Silenced `template-extend-render` warning in tests output. Closes #151.

t/151: Silenced a warning in tests output

---

src/list/listitemview.js
tests/list/listitemview.js

Feature: Enabled styling via "class" attribute in ListItemView. Closes #162.

t/162: Enable styling via class attribute in ListItemView.

---

src/list/listitemview.js
tests/list/listitemview.js

Feature: Allowed marking ListItemView active using the #isActive attribute. Closes #166.
---
* Requires https://github.com/ckeditor/ckeditor5-ui/pull/163.

t/166: Allowed marking ListItemView active using the #isActive attribute

---

src/contextualballoon.js
tests/contextualballoon.js
tests/manual/contextualballoon/contextualballoon.html
tests/manual/contextualballoon/contextualballoon.js
tests/manual/contextualballoon/contextualballoon.md

Feature: Introduced `ContextualBalloon` plugin for managing contextual balloons. Closes #134.
---
- #178 - Improve ContextualBalloon positioning.
- #185 - Improve ContextualBalloon manual test.
- #179 - Custom action when panel of ContextualBalloon becomes visible.
- #186 - Component to manage a stack of child views.

Introduced ContextualBalloon class for managing contextual balloons.

---

src/button/buttonview.js
src/focuscycler.js
tests/button/buttonview.js
tests/focuscycler.js
theme/helpers/_states.scss

Fix: `FocusCycler` should ignore invisible views. Closes #209.

T/209: FocusCycler should not consider invisible views.

---

src/panel/balloon/balloonpanelview.js
tests/panel/balloon/balloonpanelview.js

Internal: Removed obsolete BalloonPanelView#maxWidth attibute, replaced by #className in the past. Closes #205.

t/205: Removed obsolete BalloonPanelView#maxWidth attibute, replaced by #className in the past

---

src/toolbar/contextual/contextualtoolbar.js
tests/toolbar/contextual/contextualtoolbar.js

Feature: Added `beforeShow` event to the `ContextualToolbar` plugin. Closes #222.

Added beforeShow event to the ContextualToolbar plugin

---

src/toolbar/contextual/contextualtoolbar.js
tests/toolbar/contextual/contextualtoolbar.js

Fix: ContextualToolbar should have proper editor toolbar styling. Closes #230.
---
Requires: https://github.com/ckeditor/ckeditor5-theme-lark/pull/90.

t/230: ContextualToolbar should have proper editor toolbar styling

---

src/panel/balloon/balloonpanelview.js
src/toolbar/contextual/contextualtoolbar.js
tests/panel/balloon/balloonpanelview.js
tests/toolbar/contextual/contextualtoolbar.js

Fix: Contextual toolbar should re–position correctly on window scroll. Closes #227.
---
Requires https://github.com/ckeditor/ckeditor5-utils/issues/157.
Also closes https://github.com/ckeditor/ckeditor5-ui/issues/195.

t/227: Contextual toolbar should re–position correctly on window scroll

---

src/dropdown/dropdownpanelview.js
tests/dropdown/dropdownpanelview.js
tests/manual/tickets/228/1.html
tests/manual/tickets/228/1.js
tests/manual/tickets/228/1.md

Fix: Clicking and dragging in a dropdown panel should not break the selection. Closes #228.

t/228: Clicking and dragging in a dropdown panel should not break the selection

---

src/panel/balloon/balloonpanelview.js
src/toolbar/contextual/contextualtoolbar.js
tests/manual/panel/balloon/balloonpanelview.html
tests/manual/panel/balloon/balloonpanelview.js
tests/manual/panel/balloon/balloonpanelview.md
tests/panel/balloon/balloonpanelview.js
tests/toolbar/contextual/contextualtoolbar.js

Other: Improvements in the `BalloonPanelView`–based components for the balloon toolbar editor. Closes #236. Closes #234. Closes #224.
BREAKING CHANGE: The position names in `BalloonPanelView.defaultPositions` and their results have changed. Please refer to the latest API documentation to learn more.
---
Requires: https://github.com/ckeditor/ckeditor5-theme-lark/pull/96

t/236: Improvements in the BalloonPanelView–based components for the balloon toolbar editor

---

src/dropdown/dropdownview.js
tests/dropdown/dropdownview.js

Fix: The dropdown menu should not open using the keyboard when disabled. Closes #238.

t/238: The dropdown menu should not open using the keyboard when disabled

---

src/panel/balloon/balloonpanelview.js
tests/panel/balloon/balloonpanelview.js

Fix: BalloonPanelView should prevent native #selectstart event. Closes #243.

t/243: BalloonPanelView should prevent native #selectstart event

---

src/panel/balloon/contextualballoon.js
src/view.js
tests/editableui/editableuiview.js
tests/editorui/editoruiview.js
tests/panel/balloon/contextualballoon.js
tests/toolbar/contextual/contextualtoolbar.js
tests/toolbar/sticky/stickytoolbarview.js
tests/view.js

Other: Made the UI destruction a fail–safe, repeatable process. Closes #248.

T/248: Made UI destruction a repeatable process

---

src/bindings/clickoutsidehandler.js
tests/bindings/clickoutsidehandler.js
tests/manual/contextualballoon/contextualballoon.js

Other: Add support for multiple context elements in `clickOutsideHandler`. Closes #261.

T/261 Add support for multiple context elements in `clickOutsideHandler`

---

src/toolbar/contextual/contextualtoolbar.js
src/toolbar/enabletoolbarkeyboardfocus.js
tests/toolbar/contextual/contextualtoolbar.js
tests/toolbar/enabletoolbarkeyboardfocus.js

Other: Implemented public show and hide methods in the ContextualToolbar plugin. Closes #263.

t/263: Implemented public show and hide methods in the ContextualToolbar plugin

---

src/inputtext/inputtextview.js
src/labeledinput/labeledinputview.js
tests/inputtext/inputtextview.js
tests/labeledinput/labeledinputview.js

Feature: Added `TextInputView#isReadOnly` and `LabeledInputView#isReadOnly`  states. Closes #266. Closes #268.

Added TextInputView#isReadOnly state.

---

src/toolbar/contextual/contextualtoolbar.js
tests/manual/contextualtoolbar/contextualtoolbar.html
tests/manual/contextualtoolbar/contextualtoolbar.js
tests/manual/contextualtoolbar/contextualtoolbar.md
tests/toolbar/contextual/contextualtoolbar.js

Feature: `ContextualToolbar#beforeShow` event is replaced by a `ContextualToolbar#show` event. `ContextualToolbar` is not displayed when all components inside are disabled. Closes #269. Closes #232.
BREAKING CHANGE: `ContextualToolbar#beforeShow` event is replaced by a `ContextualToolbar#show`.

ContextualToolbar is not displayed when all components inside are disabled.

---

src/toolbar/normalizetoolbarconfig.js
src/toolbar/sticky/stickytoolbarview.js
tests/manual/stickytoolbarview/stickytoolbarview.html
tests/manual/stickytoolbarview/stickytoolbarview.js
tests/manual/stickytoolbarview/stickytoolbarview.md
tests/toolbar/normalizetoolbarconfig.js
tests/toolbar/sticky/stickytoolbarview.js

Other: `StickyToolbarView` should support a configurable vertical offset from the top of the page. Closes #277.
Also implemented the `normalizeToolbarConfig()` utility.
BREAKING CHANGE: `StickyToolbarView#limiterOffset` has been renamed to `StickyToolbarView#limiterBottomOffset`.

t/277: StickyToolbarView should support a configurable vertical offset from the top of the page

---

src/button/buttonview.js
src/tooltip/tooltipview.js
tests/button/buttonview.js
tests/tooltip/tooltipview.js
theme/components/tooltip.scss

Fix: Button tooltip should not look blurry on ldpi screens. Closes #142. Closes #133.
BREAKING CHANGE: The `ck-tooltip__main`, `ck-tooltip__arrow` and `ck-tooltip__elements` mixins are no longer available. CSS classes should be used instead.
---
* Requires https://github.com/ckeditor/ckeditor5-theme-lark/pull/104.

t/142: Button tooltip should not look blurry on ldpi screens

---

src/button/buttonview.js
src/tooltip/tooltipview.js
tests/button/buttonview.js
tests/tooltip/tooltipview.js

Fix: `ButtonView#tooltip` can be added and removed after `ButtonView` initialization. Closes #283.

ButtonView#tooltip can be added and removed after ButtonView initialization.

---

src/bindings/clickoutsidehandler.js
tests/bindings/clickoutsidehandler.js

Fix: The `clickOutsideHandler` helper should use `mousedown` instead of `mouseup` event. Closes #281.
---
Should be merged with related branches:
* https://github.com/ckeditor/ckeditor5-image/tree/t/ckeditor5-ui/281
* https://github.com/ckeditor/ckeditor5-link/tree/t/ckeditor5-ui/281

t/281: The clickOutsideHandler helper should use mousedown instead of mouseup event

---

src/template.js
tests/template.js

Fix: The `Template` class will not throw an error if its child does not have an `idProperty`. Closes #289.

T/289: Changed type of collection used in "Template" class.

---

src/panel/balloon/balloonpanelview.js
tests/panel/balloon/balloonpanelview.js
theme/components/panel/balloonpanel.scss

Fix: Removed hacks from `BalloonPanelView` that made BalloonPanel content unselectable. Closes #294. Closes https://github.com/ckeditor/ckeditor5/issues/498.
---
@Mgsy could confirm this PR does not make a regression especially for this issues:
- https://github.com/ckeditor/ckeditor5-link/issues/126
- https://github.com/ckeditor/ckeditor5-link/issues/90

Fix: Removed hacks from `BalloonPanelView` that made BalloonPanel unselectable

---

src/componentfactory.js
src/toolbar/toolbarview.js
tests/componentfactory.js
tests/toolbar/toolbarview.js

Other: ToolbarView#fillFromConfig should warn when the factory does not provide a component. Closes #291. Closes https://github.com/ckeditor/ckeditor5/issues/526.
---
* Could close https://github.com/ckeditor/ckeditor5/issues/526.

t/291: ToolbarView#fillFromConfig should warn when the factory does not provide a component

---

src/view.js
tests/view.js

Feature: Implemented `View#removeChildren`, the opposite of `View#addChildren`. Closes #303.

t/303: Implemented View#removeChildren

---

src/panel/balloon/contextualballoon.js
tests/panel/balloon/contextualballoon.js

Fix: `ContextualBalloon` should remember position passed to `#updatePosition`. Closes #305. Closes ckeditor/ckeditor5-image#141.

t/305: ContextualBalloon should remember position passed to #updatePosition

---

src/toolbar/contextual/contextualtoolbar.js
tests/toolbar/contextual/contextualtoolbar.js

Fix: ContextualToolbar should not be positioned to a zero–width DOM rect when invoked for a multi-line forward selection. Closes #308.

t/308: ContextualToolbar should not be positioned to a zero–width DOM rect when invoked for a multi-line forward selection

---

theme/components/panel/stickypanel.scss

Fix: Fixed sticky panel positioning when above images. Closes #315.
---
Sticky panel which holds the toolbar have `position:fixed` applied, so the elements inside editor with `position:relative` (images for example) are positioned above the sticky panel. Browser compares `z-index` of the sticky panel (which is not set) instead of panel's `z-index: 999`.

Adding z-index to sticky panel when position: fixed is applied

---

src/componentfactory.js
tests/componentfactory.js

Enhancement: Make `ComponentFactory` case-insensitive. Closes #324.
Defining toolbar components should not fail if someone use different case than defined by pluign.
---
* I've added internal method that ensures `name` is a string before executing `.toLowerCase()` just to not have `trying to call .toLowerCase() of undefined` in console.

Enhancement: Make ComponentFactory case-insensitive.

---

src/template.js
tests/template.js

Fix: Template#getViews generator should not traverse native HTML elements. Closes #337. Closes ckeditor/ckeditor5#657.

t/337: Template#getViews generator should not traverse native HTML elements

---

src/editorui/boxed/boxededitoruiview.js

Other: Aligned code to changes (`config.lang` to `config.languages`). Part of the Translation Service v2 (ckeditor/ckeditor5#624).

Align code to changed config.lang to config.languages

---

src/icon/iconview.js
tests/button/buttonview.js
tests/icon/iconview.js
tests/manual/icon/icon.html
tests/manual/icon/icon.js
tests/manual/icon/icon.md

Fix: It should be possible to use "dirty" third-party SVGs as the content of the IconView. Closes #350.

t/350: It should be possible to use "dirty" third-party SVGs as the content of the IconView

---

src/dropdown/utils.js
src/view.js
tests/dropdown/button/createbuttondropdown.js
tests/dropdown/list/createlistdropdown.js
tests/view.js

Other: The `closeDropdownOnBlur` helper should use `clickOutsideHandler`. Decorated `View#render` method. Closes #311.
---
A successor to https://github.com/ckeditor/ckeditor5-ui/pull/312.

t/311a: The closeDropdownOnBlur helper should use clickOutsideHandler

---

docs/_snippets/examples/bootstrap-ui-inner.html
docs/framework/guides/external-ui.md

Docs: Changed hex/rgb format to hsl/a in some css classes. 
* Related to https://github.com/ckeditor/ckeditor5-theme-lark/issues/124.

t/ckeditor5-theme-lark/124: Standarized colors to hsl/a format.

---

src/editableui/editableuiview.js
tests/editableui/editableuiview.js

Other: Added the `.ck-content` CSS class to the `EditableUIView`. Closes #176.
---
To be merged along with https://github.com/ckeditor/ckeditor5/compare/t/ckeditor5-ui/176?expand=1.

t/176: Added the .ck-content CSS class to the EditableUIView

---

src/editorui/boxed/boxededitoruiview.js
tests/editorui/boxed/boxededitoruiview.js
theme/components/label/label.css

Other: CSS classes should be prefixed with `ck-` instead of `cke-`. Closes #112.

t/112: CSS classes should be prefixed with ck- instead of cke-

---

src/toolbar/contextual/contextualtoolbar.js
tests/toolbar/contextual/contextualtoolbar.js

BREAKING CHANGE:  Removed `.ck-editor-toolbar` class in `ToolbarView`  and `.ck-editor-toolbar-container` class in `balloonClassName`.
---
* A piece of https://github.com/ckeditor/ckeditor5-theme-lark/issues/135

Removed `.ck-editor-toolbar` and `.ck-editor-toolbar-container` classes.

---

src/dropdown/button/splitbuttonview.js
tests/dropdown/button/splitbuttonview.js
theme/components/dropdown/splitbutton.css

Other: Added a CSS class to the `SplitButtonView` when the arrow is on (see ckeditor/ckeditor5-theme-lark#134).

t/ckeditor5-theme-lark/134: Added a CSS class to the `SplitButtonView` when the arrow is on

---

src/button/buttonview.js
src/icon/iconview.js
tests/button/buttonview.js
tests/icon/iconview.js
theme/components/icon/icon.css

Feature: Implemented the `IconView#fillColor` observable which fills child `.ck-icon__fill` paths  with the color (see ckeditor/ckeditor5-theme-lark#148).
Also made the `ButtonView#iconView` present by default to allow easy `IconView#fillColor` bindings in the component factory.

t/ckeditor5 theme lark/148: Feature: Implemented the `IconView#fillColor` observable

---

src/componentfactory.js
tests/componentfactory.js

Other: `ComponentFactory.names()` will return original component names (instead of normalized names). Closes #376.

Made ComponentFactory.names() return original componenent name.

---

docs/_snippets/examples/bootstrap-ui-inner.js
docs/framework/guides/external-ui.md

Internal: Do not use `loadDataFromElement` after it was removed in #ckeditor5-core/120.

Docs: Align samples with new Editor API.

---

docs/_snippets/examples/bootstrap-ui-inner.js
docs/framework/guides/external-ui.md

Docs: Update external UI guide to the latest changes in heading feature API. Closes ckeditor/ckeditor5#893.
---

Fix: The bootstrap (external UI) example is up.

---

src/view.js
tests/view.js

Other: Renamed plural method names to singular. See ckeditor/ckeditor5#742.
BREAKING CHANGES: `ui/view~View#registerChildren` and `ui/view~View#deregisterChildren` have been renamed to `ui/view~View#registerChild` and `ui/view~View#deregisterChild`.
---
Should be merged together with:
- https://github.com/ckeditor/ckeditor5-editor-balloon/pull/16
- https://github.com/ckeditor/ckeditor5-editor-decoupled/pull/12
- https://github.com/ckeditor/ckeditor5-editor-decoupled/pull/12
Changed `mgit.json` – https://github.com/ckeditor/ckeditor5-engine/pull/1389#issuecomment-377192059.

Renamed plural method names to singular

---

theme/components/tooltip/mixins/_tooltip.css

Fix: The action should be executed upon the first click on a tooltip-enabled UI in iOS. Closes ckeditor/ckeditor5#920.

t/ckeditor5/920b: The action should be executed upon the first click on a tooltip-enabled UI in iOS

---

src/dropdown/utils.js
src/list/listseparatorview.js
tests/dropdown/utils.js
tests/list/listseparatorview.js
theme/components/list/list.css

Feature: Implemented list component separators (see ckeditor/ckeditor5-table#24).
---
Part of https://github.com/ckeditor/ckeditor5-table/pull/46.

t/ckeditor5-table/24: Implemented list component separators

---

src/toolbar/balloon/balloontoolbar.js
src/toolbar/block/blocktoolbar.js
tests/toolbar/balloon/balloontoolbar.js
tests/toolbar/block/blocktoolbar.js

Internal: Used UI#update event instead of View#render to attach the UI components.
---
- https://github.com/ckeditor/ckeditor5-core/pull/131

Used UI#update event instead of View#render to attach the UI components.

---

src/toolbar/balloon/balloontoolbar.js
tests/manual/tickets/418/1.html
tests/manual/tickets/418/1.js
tests/manual/tickets/418/1.md
tests/toolbar/balloon/balloontoolbar.js

Fix: Hide the BalloonToolbar on editable blur. Closes #418.
---

Hide the BalloonToolbar on editable blur

---

src/toolbar/block/blocktoolbar.js
tests/toolbar/block/blocktoolbar.js

Fix: Hide BlockToolbar when the editor is blurred. Closes #408.
---

Fix: Hide BlockToolbar when the editor is blurred.

---

src/toolbar/balloon/balloontoolbar.js
tests/manual/tickets/418/1.js
tests/toolbar/balloon/balloontoolbar.js

Fix: Used editableElement after uiReady. Closes #424.
---

Used editableElement after uiReady

---

theme/components/list/list.css
theme/components/panel/balloonpanel.css

Other: Allowed list item's buttons to have an outer, visible `box-shadow`. Ensured the balloon panel's arrow does not cover panel's children. Closes #394.
---
**Note**: This is a piece of the constellation https://github.com/ckeditor/ckeditor5/tree/t/ckeditor5-ui/394 containing the following PRs:
* https://github.com/ckeditor/ckeditor5-theme-lark/pull/187 (the best part of the PR)
* https://github.com/ckeditor/ckeditor5-paragraph/pull/35 (icon)
* https://github.com/ckeditor/ckeditor5-heading/pull/109 (icons)
* https://github.com/ckeditor/ckeditor5-core/pull/136 (icon)
**Note**: Please build docs and check out all guides/examples when reviewing.
**Note**: Screenshots from Letters would also help /cc @dkonopka

t/394: Block toolbar improvements

---

docs/_snippets/features/blocktoolbar.html
docs/_snippets/features/blocktoolbar.js
docs/features/blocktoolbar.md

Docs: Added the block toolbar feature guide. Closes ckeditor/ckeditor5#1058.

t/ckeditor5/1058: Added the block toolbar documentation.

---

docs/_snippets/features/blocktoolbar.html
docs/_snippets/features/blocktoolbar.js
docs/features/blocktoolbar.md
package.json

Docs: Improved the block toolbar guide by using the balloon editor instead of the classic editor to showcase the integration. Closes #427.

t/427: Docs: Improved the block toolbar guide by using the balloon editor instead of the classic editor to showcase the integration

---

package.json
src/model.js
src/panel/balloon/balloonpanelview.js
src/template.js
src/toolbar/balloon/balloontoolbar.js

Internal: Replaced `ckeditor5-uitls/src/lib/lodash` imports with `lodash-es`.
---
Part of the https://github.com/ckeditor/ckeditor5-utils/pull/252.

Replace `ckeditor5-uitls/src/lib/lodash` imports with `lodash-es`

---

src/dropdown/dropdownpanelview.js
src/dropdown/dropdownview.js
src/dropdown/utils.js
tests/dropdown/dropdownpanelview.js
tests/dropdown/dropdownview.js
tests/dropdown/manual/dropdown.js
tests/dropdown/manual/panelposition.html
tests/dropdown/manual/panelposition.js
tests/dropdown/manual/panelposition.md
theme/components/dropdown/dropdown.css

Feature: Implemented configurable, smart `DropdownView` panel positioning. Closes #123.
Also fixed some dropdown–related documentation and manual tests.
---
I fixed some outdated docs and manual tests in this branch, which were abandoned as the API changed in the past. The UI framework guide also needed revisiting and changes are in a [separate PR in the root repository](https://github.com/ckeditor/ckeditor5/pull/1296), so it's nice if they were verified and merged too.

t/123: Implemented smart `DropdownView` panel positioning

---

src/editableui/editableuiview.js
tests/editableui/editableuiview.js

Other: Added the `.ck-read-only` CSS class to the `EditableUIView` when `view#isReadOnly` is true. 
---
Part of: https://github.com/ckeditor/ckeditor5-theme-lark/pull/208

Added `.ck-read-only` class to `EditableUIView`

---

src/panel/balloon/balloonpanelview.js
src/panel/balloon/contextualballoon.js
src/toolbar/block/blocktoolbar.js
src/toolbar/toolbarview.js
tests/panel/balloon/balloonpanelview.js
tests/panel/balloon/contextualballoon.js
tests/toolbar/block/blocktoolbar.js
tests/toolbar/toolbarview.js

Other: Use class as class-controlling property of ui components. Closes #450.
BREAKING CHANGE: The `BallonPanelView#className` property was renamed to `#class`.
BREAKING CHANGE: The `ToolbarView#className` property was renamed to `#class`.
---
* Changes in other repos:
- ckeditor5: https://github.com/ckeditor/ckeditor5/pull/1407
- theme-lark: https://github.com/ckeditor/ckeditor5-theme-lark/pull/212

Use class as class-controlling property of ui components.

---

tests/manual/tickets/170/1.js
tests/toolbar/balloon/balloontoolbar.js
tests/toolbar/block/blocktoolbar.js

Tests: Remove all usages of `view.editableElement`.
---
Reporting ticket is https://github.com/ckeditor/ckeditor5/issues/1489.

Tests: Remove all usages of `view.editableElement`

---

src/editableui/editableuiview.js
src/editableui/inline/inlineeditableuiview.js
tests/editableui/editableuiview.js
tests/editableui/inline/inlineeditableuiview.js
tests/toolbar/balloon/balloontoolbar.js

Internal: Moved the `EditableUIView` and  `InlineEditableUIView` attributes management to the engine (see ckeditor/ckeditor5#479). Closes ckeditor/ckeditor5#798.
BREAKING CHANGE: The `EditableUIView#isReadOnly` property has been removed. Use the engine `EditableElement#isReadOnly` instead.
BREAKING CHANGE: The second argument of `EditableUIView.constructor()` and `InlineEditableUIView.constructor()` became the instance of the editing view (previously an optional editable element reference).
---
Part of the [constellation](https://github.com/ckeditor/ckeditor5/tree/t/479).

T/ckeditor5/479: Moved the editable attributes management to the engine

---

docs/_snippets/examples/bootstrap-ui-inner.html
docs/framework/guides/external-ui.md

Internal: Used the `.ck-read-only` class instead `[contenteditable]` CSS Selector. Closes https://github.com/ckeditor/ckeditor5/issues/1343).

Using the `.ck-read-only` class instead contenteditable CSS Selector.

---

src/editableui/editableuiview.js
tests/editableui/editableuiview.js

Fix: Prevented from changing the view document during the render phase. Closes https://github.com/ckeditor/ckeditor5/issues/1530.
---
Requires: https://github.com/ckeditor/ckeditor5-engine/pull/1682.

Prevented from changing view document during the render phase.

---

docs/_snippets/examples/bootstrap-ui-inner.js
docs/framework/guides/external-ui.md

Docs: Revived the Third-party (Bootstrap) UI guide and example after refactoring in the `EditableUIView` class (ckeditor/ckeditor5-ui#463). Closes ckeditor/ckeditor5#1549.

t/ckeditor5/1549: Revived the Third-party (Bootstrap) UI guide and example after refactoring in the EditableUIView class

---

src/editableui/editableuiview.js
tests/editableui/editableuiview.js

Fix: Fixed `View#render` collision when moving focus from a one editable to the other in multi-root editor. Closes https://github.com/ckeditor/ckeditor5/issues/1676.
---

Fix: Fixed View#render collision when moving focus from a one editable to the other in multi-root editor

---

src/template.js

Docs: Corrected `Template#apply()` docs code listing. Closes ckeditor/ckeditor5#1648.
---
I added more context variable to make it easy to copy'n'paste the code snippet and continue to experiment with it and removed `on` property.
Also renamed the `attrs` property into `attributes` and renamed `attrs` in `Template.bind()` which is outside of the scope of this issue, but it's not worth to make a dedicated issue for this one.

Corrected Template#apply() docs code listing

---

src/panel/balloon/contextualballoon.js
tests/panel/balloon/contextualballoon.js

Other: The `ContextualBalloon` plugin's `add` method now accepts the `withArrow` option. Closes #487.
---
I've assumed that:
* The `withArrow` name should be the same as `BalloonPanelView` property.
* The default value is `true` for backwards compatibilty.
The PR is required for: https://github.com/ckeditor/ckeditor5-mention/pull/60 (to show/hide the arrow).

Add withArrow option to ContextualBalloon#add() method.

---

theme/components/panel/balloonrotator.css

Fix: Rotatable balloons should center toolbar items. Closes #495.
---

Rotatable balloons should center toolbar items

---

src/panel/balloon/balloonpanelview.js
src/panel/balloon/contextualballoon.js
tests/manual/contextualballoon/contextualballoon.html
tests/manual/contextualballoon/contextualballoon.js
tests/manual/contextualballoon/contextualballoon.md
tests/panel/balloon/balloonpanelview.js
tests/panel/balloon/contextualballoon.js
theme/components/panel/fakepanel.css

Other: Improved UX of ContextualBalloon with multiple stacks. Closes #501.
---
Required: `ckeditor5-theme-lark#cf/2808` https://github.com/ckeditor/ckeditor5-theme-lark/pull/229

Introduced FakePanels for ContextualBalloon.

---

src/notification/notification.js

Docs: Lang corrections for API docs of the `Notification#showWarning()` method.
---
It _partially_ addresses ckeditor/ckeditor5#1773.

API docs corrections for the Notification#showWarning() method

---

docs/_snippets/examples/bootstrap-ui-inner.js
docs/framework/guides/external-ui.md

Docs: Used the new `EditorUI#setEditableElement()` API in the custom editor guides (see ckeditor/ckeditor5#1838).
---
A piece of https://github.com/ckeditor/ckeditor5/pull/1840.

t/ckeditor5/1838: Docs: Used the new `EditorUI#setEditableElement()` API in the custom editor guides

---

src/componentfactory.js
src/panel/balloon/contextualballoon.js
src/template.js
src/view.js
src/viewcollection.js
tests/componentfactory.js
tests/dropdown/utils.js
tests/panel/balloon/contextualballoon.js
tests/template.js
tests/view.js
tests/viewcollection.js

Internal: Aligned code to introduced error context. Required by ckeditor/ckeditor5-watchdog#2.
---

Aligned code to introduced error context

---

src/labeledinput/labeledinputview.js
tests/labeledinput/labeledinputview.js

Other: Add `role="alert"` to error notification in label input view. Closes ckeditor/ckeditor5#1406.
---

Add role="alert" to error notification in label input view

---

src/template.js
src/toolbar/toolbarview.js
tests/template.js
tests/toolbar/toolbarview.js

Internal: Removed usage of the CKEditor 5 logger. Part of ckeditor/ckeditor5#383.
---

Removed usage of logger.

---

docs/features/blocktoolbar.md

Docs: Add links to balloon block editor in balloon toolbar docs. Closes: ckeditor/ckeditor5#1550.

Add links to balloon block editor in balloon toolbar docs

---

src/button/button.jsdoc
src/button/buttonview.js
src/button/switchbuttonview.js
src/dropdown/button/splitbuttonview.js
src/toolbar/block/blockbuttonview.js
tests/button/buttonview.js
tests/button/switchbuttonview.js
tests/dropdown/button/splitbuttonview.js
tests/toolbar/block/blockbuttonview.js

Fix: Improve the functionality of `aria-pressed` attribute in button elements. Closes ckeditor/ckeditor5#1403.
---
sub-pr:
* https://github.com/ckeditor/ckeditor5-alignment/pull/44
* https://github.com/ckeditor/ckeditor5-basic-styles/pull/95
* https://github.com/ckeditor/ckeditor5-block-quote/pull/40
* https://github.com/ckeditor/ckeditor5-heading/pull/128
* https://github.com/ckeditor/ckeditor5-highlight/pull/43
* https://github.com/ckeditor/ckeditor5-image/pull/303
* https://github.com/ckeditor/ckeditor5-link/pull/246
* https://github.com/ckeditor/ckeditor5-list/pull/135
* https://github.com/ckeditor/ckeditor5-paragraph/pull/46

Improve the functionality of `aria-pressed` attribute in button elements

---

src/toolbar/toolbarview.js
tests/manual/toolbar/grouping.html
tests/manual/toolbar/grouping.md
tests/toolbar/toolbarview.js

Internal: Automatic toolbar grouping dropdown should not be auto-positioned. Closes ckeditor/ckeditor5#5608.

i/5608: Automatic toolbar grouping dropdown should not be auto-positioned

---

src/button/button.jsdoc
src/button/buttonview.js
tests/button/buttonview.js

Feature: Enabled keystroke preview in `ButtonView`. Implemented the `ButtonView#withKeystroke` property. Closes ckeditor/ckeditor5#5782.
---
Requires: https://github.com/ckeditor/ckeditor5-theme-lark/pull/252 (styles)

i/5782: Enabled keystroke preview in `ButtonView`

---

src/toolbar/block/blocktoolbar.js
tests/toolbar/block/blocktoolbar.js

Fix: Make `BlockToolbar` work with an empty configuration. Closes ckeditor/ckeditor5#5980.
---
* As discussed in https://github.com/ckeditor/ckeditor5-ui/pull/532 the block toolbar should work with empty toolbar configuration as other features use this pattern.

Make BlockToolbar work with empty configuration.

---

tests/dropdown/dropdownview.js

Tests: Fixed tests leaking editor instances / DOM elements. See ckeditor/ckeditor5#6002.
---
For a complete list of PRs see https://github.com/ckeditor/ckeditor5/issues/6002#issuecomment-567834563.

Fixed tests leaking editor instance / DOM element.

---

src/toolbar/toolbarview.js
tests/toolbar/toolbarview.js

Feature: Implemented the `Toolbar#isCompact` property to turn regular toolbars into compact ones (with less spacing) (see ckeditor/ckeditor5#6112)
---
A piece of https://github.com/ckeditor/ckeditor5-table/pull/232.

I/6112: Implemented the `Toolbar#isCompact` property

---

src/toolbar/toolbarview.js
tests/toolbar/toolbarview.js

Internal: Aligned the `ToolbarView` class (and tests) to the `ResizeObserver` that replaced the `getResizeObserver()` helper (see ckeditor/ckeditor5#6145).
---
A piece of https://github.com/ckeditor/ckeditor5-utils/pull/320.

i/6145: Aligned the `ToolbarView` class to the `ResizeObserver`

---

src/dropdown/dropdownview.js
tests/dropdown/dropdownview.js

Other: Removed the obsolete `DropdownView#focusTracker`. Closes ckeditor/ckeditor5#6548.
BREAKING CHANGE: The `DropdownView#focusTracker` property has been removed.

i/6548: Removed the obsolete DropdownView#focusTracker.
